version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      time: "00:00"
      timezone: Europe/Berlin
    assignees:
      - marcel-breuer

  - package-ecosystem: npm
    directory: /apps/web
    schedule:
      interval: monthly
      time: "00:00"
      timezone: Europe/Berlin
    assignees:
      - marcel-breuer

  - package-ecosystem: pip
    directory: /backend
    schedule:
      interval: monthly
      time: "00:00"
      timezone: Europe/Berlin
    assignees:
      - marcel-breuer
