"""add local authentication fields.

Revision ID: 02edca43c36f
Revises: afecd4d958df
Create Date: 2026-09-09 21:07:24.167531
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "02edca43c36f"
down_revision: str | None = "afecd4d958df"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("username", sa.Text(), nullable=True))
    op.add_column("users", sa.Column("password_hash", sa.Text(), nullable=True))
    op.add_column("users", sa.Column("role", sa.String(length=16), nullable=True))
    op.execute("UPDATE users SET password_hash = '!' WHERE password_hash IS NULL")
    op.execute("UPDATE users SET role = 'admin' WHERE role IS NULL")
    op.alter_column("users", "password_hash", existing_type=sa.TEXT(), nullable=False)
    op.alter_column("users", "role", existing_type=sa.VARCHAR(length=16), nullable=False)
    op.alter_column("users", "email", existing_type=sa.TEXT(), nullable=True)
    op.create_unique_constraint("uq_users_username", "users", ["username"])
    op.create_check_constraint("ck_user_role", "users", "role IN ('admin', 'user')")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_user_role", "users", type_="check")
    op.drop_constraint("uq_users_username", "users", type_="unique")
    op.alter_column("users", "email", existing_type=sa.TEXT(), nullable=False)
    op.drop_column("users", "role")
    op.drop_column("users", "password_hash")
    op.drop_column("users", "username")
    # ### end Alembic commands ###
